name: planetary_arosics
channels:
  - conda-forge
  - defaults
dependencies:
  - arosics>=1.3.0
  - bs4
  - gdal
  - ghostscript=9.56.1
  - gmt=6.3.0
  - numpy
  - pip
  - pygmt=0.6.1
  - python
  - pyproj
  - rasterio
  - ipykernel
  - pip:
    - pdr